# Generated by Django 6.0.2 on 2026-03-28 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Category name must be les then 50 characters!', 'unique': 'The name already exists!'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Flower name must be les then 50 characters!'}, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(error_messages={'max_length': 'Customer name must be les then 50 characters!'}, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(error_messages={'max_length': 'Customer phone must be les then 50 characters!'}, max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
