# Generated by Django 6.0.2 on 2026-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='photo',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
