# Generated by Django 6.0.2 on 2026-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_flower_photo_category_image_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
